import type {
  AdminDashboardStats,
  CertificateRecord,
  Course,
  CourseBlueprint,
  Enrollment,
  InmateProfile,
  ManagementAnalyticsSnapshot,
  ProgressSnapshot,
  ReportRecord,
} from "@/types/domain";

export const appMeta = {
  name: "Ghana Prisons Learning Portal",
  offlineLabel: "Connected to Local Server - Secure Offline Environment",
};

export const courseCategories = [
  "IT & Digital Skills",
  "Languages",
  "Management",
  "Technical & Vocational",
];

export const topRatedCourses: Course[] = [
  {
    id: "C-001",
    title: "Website Development",
    category: "IT & Digital Skills",
    instructor: "Mr. K. Johnson",
    rating: 4.8,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Foundations in web layout, navigation, and building responsive pages for modern digital work.",
    level: "Beginner",
    durationHours: 28,
    status: "active",
    updatedAt: "2026-02-24T09:30:00.000Z",
  },
  {
    id: "C-002",
    title: "Computer Programming (Python)",
    category: "IT & Digital Skills",
    instructor: "Ms. A. Daniels",
    rating: 4.6,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Introductory Python concepts, logic, and scripting for practical problem solving.",
    level: "Beginner",
    durationHours: 30,
    status: "active",
    updatedAt: "2026-02-23T12:10:00.000Z",
  },
  {
    id: "C-003",
    title: "Data Analytics",
    category: "IT & Digital Skills",
    instructor: "Mrs. E. Boateng",
    rating: 4.9,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Learn data collection, spreadsheet analysis, and interpretation for evidence-based decisions.",
    level: "Intermediate",
    durationHours: 26,
    status: "active",
    updatedAt: "2026-02-21T15:00:00.000Z",
  },
  {
    id: "C-004",
    title: "Basic Computer Skills",
    category: "IT & Digital Skills",
    instructor: "Mr. Owusu",
    rating: 4.5,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Keyboard use, file management, and safe computing habits for entry-level digital literacy.",
    level: "Beginner",
    durationHours: 24,
    status: "active",
    updatedAt: "2026-02-22T08:40:00.000Z",
  },
  {
    id: "C-005",
    title: "Microsoft Office Suite",
    category: "IT & Digital Skills",
    instructor: "Mrs. A. Boadi",
    rating: 4.4,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Practical use of Word, Excel, and PowerPoint for office productivity and reporting.",
    level: "Intermediate",
    durationHours: 22,
    status: "active",
    updatedAt: "2026-02-20T11:25:00.000Z",
  },
  {
    id: "C-006",
    title: "Computer Networking",
    category: "IT & Digital Skills",
    instructor: "Mr. T. Mensah",
    rating: 4.3,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Understand devices, internet connectivity, and core networking concepts for workplace readiness.",
    level: "Beginner",
    durationHours: 20,
    status: "active",
    updatedAt: "2026-02-19T10:05:00.000Z",
  },
  {
    id: "C-007",
    title: "Graphic Designing",
    category: "IT & Digital Skills",
    instructor: "Ms. Efua Nartey",
    rating: 4.7,
    thumbnail: "/assets/education/hero-library.jpg",
    summary: "Build visual communication skills for posters, branding, and digital content creation.",
    level: "Intermediate",
    durationHours: 24,
    status: "active",
    updatedAt: "2026-02-18T09:00:00.000Z",
  },
  {
    id: "C-008",
    title: "Photography and Photo Editing",
    category: "IT & Digital Skills",
    instructor: "Mr. Kwaku Addo",
    rating: 4.5,
    thumbnail: "/assets/education/hero-learning.jpg",
    summary: "Capture strong images and improve them with practical photo-editing workflows.",
    level: "Intermediate",
    durationHours: 18,
    status: "active",
    updatedAt: "2026-02-18T09:10:00.000Z",
  },
  {
    id: "C-009",
    title: "Video Editing",
    category: "IT & Digital Skills",
    instructor: "Ms. Linda Owusu",
    rating: 4.4,
    thumbnail: "/assets/education/hero-library.jpg",
    summary: "Edit clips, add transitions, and prepare simple video stories for training and outreach.",
    level: "Intermediate",
    durationHours: 20,
    status: "active",
    updatedAt: "2026-02-18T09:20:00.000Z",
  },
  {
    id: "C-010",
    title: "Artificial Intelligence",
    category: "IT & Digital Skills",
    instructor: "Mr. Daniel Tetteh",
    rating: 4.9,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Understand AI fundamentals, responsible use, and practical ways AI supports learning and work.",
    level: "Advanced",
    durationHours: 26,
    status: "active",
    updatedAt: "2026-02-18T09:30:00.000Z",
  },
  {
    id: "C-011",
    title: "Introduction to CCTV and DSTV Installation",
    category: "IT & Digital Skills",
    instructor: "Mr. Isaac Lamptey",
    rating: 4.6,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Install, configure, and maintain basic CCTV and DSTV systems safely.",
    level: "Intermediate",
    durationHours: 24,
    status: "active",
    updatedAt: "2026-02-18T09:40:00.000Z",
  },
  {
    id: "C-012",
    title: "Computer system for business",
    category: "IT & Digital Skills",
    instructor: "Ms. Mavis Aidoo",
    rating: 4.3,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Use information systems to support records, communication, and business operations.",
    level: "Beginner",
    durationHours: 18,
    status: "active",
    updatedAt: "2026-02-18T09:50:00.000Z",
  },
  {
    id: "C-013",
    title: "Database Management",
    category: "IT & Digital Skills",
    instructor: "Mr. Emmanuel Asare",
    rating: 4.7,
    thumbnail: "/assets/education/course-computer.jpg",
    summary: "Organize, store, and retrieve structured data for administration and reporting tasks.",
    level: "Intermediate",
    durationHours: 22,
    status: "active",
    updatedAt: "2026-02-18T10:00:00.000Z",
  },
  {
    id: "C-014",
    title: "English Speaking and Writing",
    category: "Languages",
    instructor: "Ms. Grace Daniels",
    rating: 4.8,
    thumbnail: "/assets/education/course-english.jpg",
    summary: "Develop confident speech, writing clarity, and everyday communication accuracy.",
    level: "Beginner",
    durationHours: 20,
    status: "active",
    updatedAt: "2026-02-18T10:10:00.000Z",
  },
  {
    id: "C-015",
    title: "French Studies",
    category: "Languages",
    instructor: "Mr. Stephen Yeboah",
    rating: 4.4,
    thumbnail: "/assets/education/course-english.jpg",
    summary: "Introductory French vocabulary, grammar, and conversation for practical use.",
    level: "Beginner",
    durationHours: 18,
    status: "active",
    updatedAt: "2026-02-18T10:20:00.000Z",
  },
  {
    id: "C-016",
    title: "Hausa",
    category: "Languages",
    instructor: "Mallam Farouk Issah",
    rating: 4.2,
    thumbnail: "/assets/education/course-english.jpg",
    summary: "Practice Hausa listening, speaking, and everyday sentence construction.",
    level: "Beginner",
    durationHours: 16,
    status: "active",
    updatedAt: "2026-02-18T10:30:00.000Z",
  },
  {
    id: "C-017",
    title: "Arabic Reading and Writing",
    category: "Languages",
    instructor: "Ustaz Karim Sulemana",
    rating: 4.5,
    thumbnail: "/assets/education/course-english.jpg",
    summary: "Build Arabic literacy through alphabet mastery, reading practice, and guided writing.",
    level: "Intermediate",
    durationHours: 18,
    status: "active",
    updatedAt: "2026-02-18T10:40:00.000Z",
  },
  {
    id: "C-018",
    title: "Communication Skills",
    category: "Languages",
    instructor: "Ms. Janet Ofori",
    rating: 4.6,
    thumbnail: "/assets/education/course-english.jpg",
    summary: "Strengthen verbal, written, and interpersonal communication for study and work.",
    level: "Beginner",
    durationHours: 16,
    status: "active",
    updatedAt: "2026-02-18T10:50:00.000Z",
  },
  {
    id: "C-019",
    title: "Time Management",
    category: "Management",
    instructor: "Mrs. Akosua Boadi",
    rating: 4.4,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Plan tasks, prioritize effectively, and improve daily productivity with simple systems.",
    level: "Beginner",
    durationHours: 14,
    status: "active",
    updatedAt: "2026-02-18T11:00:00.000Z",
  },
  {
    id: "C-020",
    title: "Money Management",
    category: "Management",
    instructor: "Mr. Kojo Annan",
    rating: 4.5,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Learn budgeting, savings habits, and responsible money decisions for daily life.",
    level: "Beginner",
    durationHours: 16,
    status: "active",
    updatedAt: "2026-02-18T11:10:00.000Z",
  },
  {
    id: "C-021",
    title: "Food Safety and Hygiene",
    category: "Management",
    instructor: "Ms. Comfort Agyemang",
    rating: 4.3,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Apply hygiene standards, storage rules, and safe food handling procedures.",
    level: "Beginner",
    durationHours: 15,
    status: "active",
    updatedAt: "2026-02-18T11:20:00.000Z",
  },
  {
    id: "C-022",
    title: "Basic Law",
    category: "Management",
    instructor: "Mr. Joseph Arthur",
    rating: 4.7,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Understand core legal principles, civic duties, and rights in practical contexts.",
    level: "Beginner",
    durationHours: 18,
    status: "active",
    updatedAt: "2026-02-18T11:30:00.000Z",
  },
  {
    id: "C-023",
    title: "First Aid",
    category: "Management",
    instructor: "Nurse Adjoa Serwaa",
    rating: 4.9,
    thumbnail: "/assets/education/course-management.jpg",
    summary: "Respond to common emergencies with safe, basic first-aid knowledge and practice.",
    level: "Beginner",
    durationHours: 12,
    status: "active",
    updatedAt: "2026-02-18T11:40:00.000Z",
  },
  {
    id: "C-024",
    title: "Fashion Designing",
    category: "Technical & Vocational",
    instructor: "Ms. Sheila Baah",
    rating: 4.7,
    thumbnail: "/assets/education/hero-learning.jpg",
    summary: "Explore design ideas, garment planning, and production steps for wearable pieces.",
    level: "Intermediate",
    durationHours: 26,
    status: "active",
    updatedAt: "2026-02-18T11:50:00.000Z",
  },
  {
    id: "C-025",
    title: "Clothing & Textiles",
    category: "Technical & Vocational",
    instructor: "Mrs. Yaa Frimpong",
    rating: 4.5,
    thumbnail: "/assets/education/hero-learning.jpg",
    summary: "Work with fabrics, measurements, and finishing methods used in clothing production.",
    level: "Intermediate",
    durationHours: 24,
    status: "active",
    updatedAt: "2026-02-18T12:00:00.000Z",
  },
  {
    id: "C-026",
    title: "Modern Carpentry",
    category: "Technical & Vocational",
    instructor: "Mr. Kwabena Owusu",
    rating: 4.8,
    thumbnail: "/assets/education/course-carpentry.jpg",
    summary: "Apply measurements, tool handling, and finishing methods in contemporary carpentry practice.",
    level: "Intermediate",
    durationHours: 30,
    status: "active",
    updatedAt: "2026-02-18T12:10:00.000Z",
  },
  {
    id: "C-027",
    title: "Modern Construction",
    category: "Technical & Vocational",
    instructor: "Mr. Seth Koomson",
    rating: 4.6,
    thumbnail: "/assets/education/course-carpentry.jpg",
    summary: "Build practical knowledge in site safety, materials, and construction workflow basics.",
    level: "Intermediate",
    durationHours: 28,
    status: "active",
    updatedAt: "2026-02-18T12:20:00.000Z",
  },
  {
    id: "C-028",
    title: "Catering",
    category: "Technical & Vocational",
    instructor: "Chef Mary Ansah",
    rating: 4.4,
    thumbnail: "/assets/education/course-entrepreneurship.jpg",
    summary: "Prepare meals, manage kitchen workflow, and deliver quality catering service.",
    level: "Beginner",
    durationHours: 22,
    status: "active",
    updatedAt: "2026-02-18T12:30:00.000Z",
  },
  {
    id: "C-029",
    title: "Draughtsmanship",
    category: "Technical & Vocational",
    instructor: "Mr. Alex Korang",
    rating: 4.3,
    thumbnail: "/assets/education/course-carpentry.jpg",
    summary: "Read and create technical drawings with accurate dimensions and clear annotations.",
    level: "Intermediate",
    durationHours: 20,
    status: "active",
    updatedAt: "2026-02-18T12:40:00.000Z",
  },
  {
    id: "C-030",
    title: "Electricals",
    category: "Technical & Vocational",
    instructor: "Mr. Samuel Lartey",
    rating: 4.8,
    thumbnail: "/assets/education/course-carpentry.jpg",
    summary: "Learn basic electrical installation, safety checks, and wiring maintenance principles.",
    level: "Intermediate",
    durationHours: 24,
    status: "active",
    updatedAt: "2026-02-18T12:50:00.000Z",
  },
];

export const courseBlueprints: CourseBlueprint[] = [
  {
    courseId: "C-001",
    updatedAt: "2026-02-24T09:30:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Web Foundations",
        objective: "Build confidence with HTML structure, page layout, and responsive design basics.",
        lessons: [
          { id: "L-001", title: "Introduction to HTML and Page Structure", type: "video", durationMinutes: 28 },
          { id: "L-002", title: "Styling and Responsive Layout Practice", type: "exercise", durationMinutes: 35 },
        ],
      },
      {
        id: "M-002",
        title: "Publishing and Iteration",
        objective: "Prepare simple websites for deployment, review, and improvement.",
        lessons: [
          { id: "L-003", title: "Navigation, Links, and Accessibility", type: "reading", durationMinutes: 22 },
          { id: "L-004", title: "Website Review and Build Assessment", type: "assessment", durationMinutes: 30 },
        ],
      },
    ],
  },
  {
    courseId: "C-002",
    updatedAt: "2026-02-23T12:10:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Python Foundations",
        objective: "Strengthen programming logic, variables, and control flow.",
        lessons: [
          { id: "L-001", title: "Syntax, Variables, and Input", type: "reading", durationMinutes: 24 },
          { id: "L-002", title: "Conditions and Loops Practice", type: "exercise", durationMinutes: 32 },
        ],
      },
    ],
  },
  {
    courseId: "C-003",
    updatedAt: "2026-02-21T15:00:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Working with Data",
        objective: "Identify patterns in data and prepare clear summaries.",
        lessons: [
          { id: "L-001", title: "Collecting and Cleaning Data", type: "video", durationMinutes: 26 },
          { id: "L-002", title: "Sorting, Filtering, and Comparison", type: "exercise", durationMinutes: 34 },
        ],
      },
      {
        id: "M-002",
        title: "Interpretation and Reporting",
        objective: "Translate numbers into practical decisions and simple reports.",
        lessons: [
          { id: "L-003", title: "Charts, Trends, and Findings", type: "reading", durationMinutes: 20 },
          { id: "L-004", title: "Analytics Scenario Assessment", type: "assessment", durationMinutes: 28 },
        ],
      },
    ],
  },
  {
    courseId: "C-004",
    updatedAt: "2026-02-22T08:40:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Computer Foundations",
        objective: "Use computers confidently and safely in daily learning tasks.",
        lessons: [
          { id: "L-001", title: "Startup, Files, and Basic Navigation", type: "reading", durationMinutes: 18 },
          { id: "L-002", title: "Keyboard, Documents, and Practice Tasks", type: "exercise", durationMinutes: 40 },
        ],
      },
    ],
  },
  {
    courseId: "C-005",
    updatedAt: "2026-02-20T11:25:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Office Productivity",
        objective: "Work effectively with core Microsoft Office applications.",
        lessons: [
          { id: "L-001", title: "Word and Document Formatting", type: "video", durationMinutes: 22 },
          { id: "L-002", title: "Excel and PowerPoint Application Tasks", type: "assessment", durationMinutes: 27 },
        ],
      },
    ],
  },
  {
    courseId: "C-006",
    updatedAt: "2026-02-19T10:05:00.000Z",
    modules: [
      {
        id: "M-001",
        title: "Network Basics",
        objective: "Understand how devices connect and exchange information securely.",
        lessons: [
          { id: "L-001", title: "Devices, Routers, and Internet Basics", type: "reading", durationMinutes: 20 },
          { id: "L-002", title: "Network Setup Practice", type: "exercise", durationMinutes: 30 },
        ],
      },
    ],
  },
];

export const inmates: InmateProfile[] = [
  {
    id: "GP-10234",
    fullName: "John Mensah",
    warrantName: "Remand Warrant",
    warrantSerialNumber: "WR-2026-001",
    prisonNumber: "GTE-10234",
    dateOfBirth: "1996-03-24",
    gender: "Male",
    station: "Nsawam Medium Security Prison",
    blockName: "Block C",
    cellNumber: "C-12",
    offense: "Stealing",
    sentence: "4 years imprisonment",
    educationBackground: "Senior High",
    skillInterests: ["Basic Computer", "Entrepreneurship"],
    blockAssignment: "Block C",
    biometricStatus: "Enrolled",
    assignedPrison: "Nsawam Medium Security Prison",
  },
  {
    id: "GP-10213",
    fullName: "Kwesi Appiah",
    warrantName: "Conviction Warrant",
    warrantSerialNumber: "WR-2026-002",
    prisonNumber: "GTE-10213",
    dateOfBirth: "1994-07-10",
    gender: "Male",
    station: "Kumasi Central Prison",
    blockName: "Block B",
    cellNumber: "B-08",
    offense: "Causing unlawful damage",
    sentence: "3 years imprisonment",
    educationBackground: "Junior High",
    skillInterests: ["Carpentry", "Personal Development"],
    blockAssignment: "Block B",
    biometricStatus: "Enrolled",
    assignedPrison: "Kumasi Central Prison",
  },
  {
    id: "GP-10215",
    fullName: "Amina Suleiman",
    warrantName: "Sentence Warrant",
    warrantSerialNumber: "WR-2026-003",
    prisonNumber: "GTE-10215",
    dateOfBirth: "1998-11-17",
    gender: "Female",
    station: "Nsawam Medium Security Prison",
    blockName: "Block D",
    cellNumber: "D-04",
    offense: "Forgery",
    sentence: "5 years imprisonment",
    educationBackground: "Vocational",
    skillInterests: ["Sales", "Digital Skills"],
    blockAssignment: "Block D",
    biometricStatus: "Enrolled",
    assignedPrison: "Nsawam Medium Security Prison",
  },
  {
    id: "GP-10219",
    fullName: "Peter Owusu",
    warrantName: "Remand Warrant",
    warrantSerialNumber: "WR-2026-004",
    prisonNumber: "GTE-10219",
    dateOfBirth: "1990-01-05",
    gender: "Male",
    station: "Kumasi Central Prison",
    blockName: "Block A",
    cellNumber: "A-03",
    offense: "Assault",
    sentence: "24 months imprisonment",
    educationBackground: "Senior High",
    skillInterests: ["Language", "Management"],
    blockAssignment: "Block A",
    biometricStatus: "Pending",
    assignedPrison: "Kumasi Central Prison",
  },
];

export const enrollments: Enrollment[] = [
  { studentId: "GP-10234", courseId: "C-001", progressPercent: 68, status: "In Progress" },
  { studentId: "GP-10234", courseId: "C-002", progressPercent: 75, status: "In Progress" },
  { studentId: "GP-10234", courseId: "C-003", progressPercent: 50, status: "In Progress" },
  { studentId: "GP-10234", courseId: "C-004", progressPercent: 40, status: "In Progress" },
  { studentId: "GP-10234", courseId: "C-006", progressPercent: 36, status: "In Progress" },
  { studentId: "GP-10213", courseId: "C-004", progressPercent: 55, status: "In Progress" },
  { studentId: "GP-10213", courseId: "C-005", progressPercent: 48, status: "In Progress" },
  { studentId: "GP-10215", courseId: "C-003", progressPercent: 82, status: "In Progress" },
  { studentId: "GP-10215", courseId: "C-006", progressPercent: 63, status: "In Progress" },
];

export const progressSnapshots: ProgressSnapshot[] = [
  {
    studentId: "GP-10234",
    activeCourses: 4,
    completedLessons: 12,
    certificatesEarned: 2,
    weeklyActivity: [2, 4, 4, 6, 5, 7],
    completionPercent: 68,
  },
];

export const adminStats: AdminDashboardStats = {
  totalInmatesRegistered: 1250,
  activeLearners: 785,
  coursesEnrolled: 1980,
  certificatesIssued: 540,
  completionRate: 63,
};

export const enrollmentDistribution = [
  { label: "Basic Computer", value: 320 },
  { label: "Languages", value: 275 },
  { label: "Management", value: 190 },
  { label: "Technical & Vocational", value: 360 },
  { label: "Personal Development", value: 250 },
  { label: "Sales & Marketing", value: 210 },
];

export const managementSnapshot: ManagementAnalyticsSnapshot = {
  enrollmentTrend: [420, 470, 510, 560, 590, 640],
  coursePopularity: [
    { label: "Technical & Vocational", value: 32 },
    { label: "IT & Digital Skills", value: 24 },
    { label: "Languages", value: 17 },
    { label: "Management", value: 15 },
    { label: "Other", value: 12 },
  ],
  completionRateByMonth: [45, 49, 52, 56, 61, 63],
  aiForecasts: [
    { label: "Projected New Enrollments", value: "740 next quarter", confidence: "88%" },
    { label: "Highest Demand Skill Area", value: "Technical & Vocational", confidence: "84%" },
    { label: "Likely Completion Uplift", value: "+6% with 2 extra mentors", confidence: "79%" },
  ],
};

export const reports: ReportRecord[] = [
  {
    id: "REP-001",
    type: "attendance",
    generatedAt: "2026-02-25T10:00:00.000Z",
    generatedBy: "Admin Officer",
  },
  {
    id: "REP-002",
    type: "performance",
    generatedAt: "2026-02-25T12:10:00.000Z",
    generatedBy: "Admin Officer",
  },
];

export const certificates: CertificateRecord[] = [
  {
    id: "CERT-001",
    studentId: "GP-10234",
    courseId: "C-001",
    issuedAt: "2026-02-20T10:00:00.000Z",
    issuedBy: "Admin Officer",
    note: "Completed Website Development competency track.",
  },
  {
    id: "CERT-002",
    studentId: "GP-10234",
    courseId: "C-002",
    issuedAt: "2026-02-24T14:30:00.000Z",
    issuedBy: "Admin Officer",
    note: "Completed Computer Programming (Python) module.",
  },
];

export const inmateGoals = [
  { label: "Complete IT & Digital Skills Course", current: 80, total: 100 },
  { label: "Earn 3 Certificates", current: 2, total: 3 },
  { label: "Read 5 Books", current: 3, total: 5 },
];
