"use client";

import { FormEvent, useEffect, useState } from "react";
import { DataTable } from "@/components/data-table";
import { RoleShell } from "@/components/role-shell";
import { fetchApi } from "@/lib/client-api";
import { formatDateTime } from "@/lib/format";
import { appMeta } from "@/lib/seed-data";
import type { ReportRecord } from "@/types/domain";

const reportTypes: Array<ReportRecord["type"]> = [
  "attendance",
  "performance",
  "course-effectiveness",
  "operational-summary",
  "executive-pack",
];

const reportFormats: Array<NonNullable<ReportRecord["format"]>> = ["pdf", "xlsx", "csv"];

export default function ManagementReportsPage() {
  const [records, setRecords] = useState<ReportRecord[]>([]);
  const [reportType, setReportType] = useState<ReportRecord["type"]>("executive-pack");
  const [format, setFormat] = useState<NonNullable<ReportRecord["format"]>>("pdf");
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function loadReports() {
    const data = await fetchApi<{ reports: ReportRecord[] }>("/api/v1/reports");
    setRecords(data.reports);
  }

  useEffect(() => {
    void loadReports().catch(() => undefined);
  }, []);

  async function onGenerate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setNotice(null);
    setError(null);
    try {
      const data = await fetchApi<{ report: ReportRecord; downloadUrl: string }>("/api/v1/reports/generate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          reportType,
          format,
          generatedBy: "Command Staff",
        }),
      });
      await loadReports();
      setNotice(`Report generated successfully. Download: ${data.downloadUrl}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to generate report.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <RoleShell title={appMeta.name} subtitle="Management - Report Packs" userName="Command Staff">
      <section className="grid-2">
        <article className="panel">
          <h2 className="section-title">Generate Management Report</h2>
          <form onSubmit={onGenerate} style={{ display: "grid", gap: 10 }}>
            <label>
              Report Type
              <select className="select" value={reportType} onChange={(event) => setReportType(event.target.value as ReportRecord["type"])}>
                {reportTypes.map((entry) => (
                  <option key={entry} value={entry}>
                    {entry}
                  </option>
                ))}
              </select>
            </label>
            <label>
              Format
              <select className="select" value={format} onChange={(event) => setFormat(event.target.value as NonNullable<ReportRecord["format"]>)}>
                {reportFormats.map((entry) => (
                  <option key={entry} value={entry}>
                    {entry.toUpperCase()}
                  </option>
                ))}
              </select>
            </label>
            <button className="button-primary" type="submit" disabled={busy}>
              {busy ? "Generating..." : "Generate Pack"}
            </button>
          </form>
          {notice ? <p className="status-ok">{notice}</p> : null}
          {error ? <p className="status-bad">{error}</p> : null}
        </article>

        <article className="panel">
          <h2 className="section-title">Export Notes</h2>
          <p className="quick-info">
            Generated reports are stored on local secure storage and can be downloaded directly within the intranet.
            Export actions are captured in the audit trail.
          </p>
          <ul className="auth-security-list" style={{ color: "var(--muted-700)", marginTop: 8 }}>
            <li>Executive pack for board-level status</li>
            <li>Attendance and operational drill-down</li>
            <li>Course effectiveness and performance tracking</li>
          </ul>
        </article>
      </section>

      <section className="panel">
        <h2 className="section-title">Generated Reports</h2>
        <DataTable
          rows={records}
          columns={[
            { key: "type", header: "Type", render: (row) => row.type },
            { key: "format", header: "Format", render: (row) => row.format?.toUpperCase() ?? "-" },
            { key: "rows", header: "Rows", render: (row) => row.rowCount ?? "-" },
            { key: "by", header: "Generated By", render: (row) => row.generatedBy },
            { key: "at", header: "Generated At", render: (row) => formatDateTime(row.generatedAt) },
            {
              key: "download",
              header: "Download",
              render: (row) =>
                row.id ? (
                  <a className="button-soft" href={`/api/v1/reports/${row.id}/download`}>
                    Download
                  </a>
                ) : (
                  "-"
                ),
            },
          ]}
          emptyLabel="No reports generated yet."
        />
      </section>
    </RoleShell>
  );
}
